
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class FitnessTracker extends javax.swing.JFrame {
    
    Activity st = new Activity("Strength Training",5, 0.006);
    Activity sm = new Activity("Swimming",4, 0.002);
    Activity run = new Activity("Running",5, 0.003);
    Activity kb = new Activity("Kickboxing",3, 0.005);
    static ArrayList<Activity> activity = new ArrayList<>(); 
    static int TotalCaloriesBurned = 0;
    static double totalheartrate = 80.0;

    /**
     * Creates new form FitnessTracker
     */
    public FitnessTracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SwimmingButton = new javax.swing.JRadioButton();
        RunningButton = new javax.swing.JRadioButton();
        StrengthTrainigButton = new javax.swing.JRadioButton();
        KickboxingButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        herebutton = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        here = new javax.swing.JButton();
        Calories = new javax.swing.JTextField();
        HeartRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Fitness Tracker");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Please choose an activity");

        buttonGroup1.add(SwimmingButton);
        SwimmingButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SwimmingButton.setSelected(true);
        SwimmingButton.setText("Swimming");
        SwimmingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmingButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(RunningButton);
        RunningButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RunningButton.setText("Running");
        RunningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunningButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(StrengthTrainigButton);
        StrengthTrainigButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StrengthTrainigButton.setText("Strength-Training");

        buttonGroup1.add(KickboxingButton);
        KickboxingButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KickboxingButton.setText("Kick-Boxing");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Please enter the time in minutes you've spent doing that activity:");

        Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS PMincho", 1, 18)); // NOI18N
        jLabel4.setText("Calories Burned:");

        jLabel5.setFont(new java.awt.Font("MS PMincho", 1, 18)); // NOI18N
        jLabel5.setText("New Heartrate:");

        addbutton.setFont(new java.awt.Font("Simplified Arabic Fixed", 3, 18)); // NOI18N
        addbutton.setText("Add New Activity");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        herebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        herebutton.setText("Calories");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("bpm");

        jLabel8.setFont(new java.awt.Font("MS PMincho", 1, 18)); // NOI18N
        jLabel8.setText("When you finish adding your activities, click");

        here.setFont(new java.awt.Font("MS PMincho", 1, 18)); // NOI18N
        here.setText("here");
        here.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hereActionPerformed(evt);
            }
        });

        Calories.setEditable(false);
        Calories.setBackground(new java.awt.Color(255, 255, 255));
        Calories.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Calories.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Calories.setText("0");
        Calories.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        Calories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaloriesActionPerformed(evt);
            }
        });

        HeartRate.setEditable(false);
        HeartRate.setBackground(new java.awt.Color(255, 255, 255));
        HeartRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HeartRate.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        HeartRate.setText("0");
        HeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeartRateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("minutes");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Please click on 'Add New Activity' to see results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3)
                    .addComponent(StrengthTrainigButton)
                    .addComponent(RunningButton)
                    .addComponent(SwimmingButton)
                    .addComponent(KickboxingButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(here))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(addbutton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(10, 10, 10)
                            .addComponent(Calories, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(herebutton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SwimmingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RunningButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StrengthTrainigButton)
                .addGap(0, 0, 0)
                .addComponent(KickboxingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Calories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(herebutton))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(here))
                .addGap(110, 110, 110))
        );

        Time.getAccessibleContext().setAccessibleName("totalTimeTrained");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed

    }//GEN-LAST:event_TimeActionPerformed

    private void SwimmingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwimmingButtonActionPerformed

    private void RunningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunningButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunningButtonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        int time = Integer.parseInt(Time.getText());

        if (SwimmingButton.isSelected()) {
            TotalCaloriesBurned += sm.getTotalCalories(time);
            totalheartrate += sm.getTotalChangeInHeartRate(totalheartrate, time);
        } else if (RunningButton.isSelected()) {
            TotalCaloriesBurned += run.getTotalCalories(time);
            totalheartrate += run.getTotalChangeInHeartRate(totalheartrate, time);
        } else if (StrengthTrainigButton.isSelected()) {
            TotalCaloriesBurned += st.getTotalCalories(time);
            totalheartrate += st.getTotalChangeInHeartRate(totalheartrate, time);
        } else {
            TotalCaloriesBurned += kb.getTotalCalories(time);
            totalheartrate += kb.getTotalChangeInHeartRate(totalheartrate, time);
        }
        String calories = Integer.toString(TotalCaloriesBurned);
        String heartrate = Double.toString(totalheartrate);
        jOptionPane1.showMessageDialog(this, "Activity added successfully!!");
        Calories.setText(calories);
        HeartRate.setText(heartrate);
    }//GEN-LAST:event_addbuttonActionPerformed

    private void hereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hereActionPerformed
        activity.add(st);
        activity.add(sm);
        activity.add(run);
        activity.add(kb);
        Activity.sortActivities(activity);
        new sorted().setVisible(true);
    }//GEN-LAST:event_hereActionPerformed

    private void CaloriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaloriesActionPerformed

    }//GEN-LAST:event_CaloriesActionPerformed

    private void HeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeartRateActionPerformed

    }//GEN-LAST:event_HeartRateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FitnessTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FitnessTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FitnessTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FitnessTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FitnessTracker().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Calories;
    private javax.swing.JTextField HeartRate;
    private javax.swing.JRadioButton KickboxingButton;
    private javax.swing.JRadioButton RunningButton;
    private javax.swing.JRadioButton StrengthTrainigButton;
    private javax.swing.JRadioButton SwimmingButton;
    private javax.swing.JTextField Time;
    private javax.swing.JButton addbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton here;
    private javax.swing.JLabel herebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables

}
